# Generated by Django 2.1.3 on 2018-11-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mileage_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField()),
                ('locations', models.CharField(max_length=120)),
                ('milesDriven', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='mileage_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mileage_entry',
            name='mileage_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mileage.mileage_user'),
        ),
    ]
