# Generated by Django 2.1.3 on 2018-11-09 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mileage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage_entry',
            name='mileage_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entry', to='Mileage.mileage_user'),
        ),
    ]
