# Generated by Django 2.1.3 on 2018-11-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mileage', '0003_auto_20181108_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mileage_entry',
            old_name='mileage_user',
            new_name='mileage_user_key',
        ),
    ]
