# Generated by Django 2.1.3 on 2018-12-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mileage', '0004_auto_20181112_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_1', models.CharField(max_length=36)),
                ('location_2', models.CharField(max_length=36)),
                ('miles_driven', models.FloatField()),
                ('date_driven', models.DateField()),
                ('mileage_user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID_trip', to='Mileage.mileage_user')),
            ],
        ),
    ]
