# Generated by Django 2.1.3 on 2018-12-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mileage', '0005_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='NickTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=36)),
                ('index', models.IntegerField()),
                ('date_driven', models.DateField()),
                ('mileage_user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mileage.mileage_user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nicktrip',
            unique_together={('location', 'index')},
        ),
    ]
