# Generated by Django 2.1.3 on 2018-12-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mileage', '0006_auto_20181209_2348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nicktrip',
            unique_together={('date_driven', 'index')},
        ),
    ]
